# Generated by Django 2.2.28 on 2025-03-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
