# Generated by Django 2.2.28 on 2025-03-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20250315_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
