# Generated by Django 2.2.28 on 2025-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20250316_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
