# Generated by Django 2.2.28 on 2025-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_useraccount_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_img',
            field=models.ImageField(upload_to='profile_img/'),
        ),
    ]
