# Generated by Django 2.2.28 on 2025-03-19 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='orders',
            field=models.ManyToManyField(blank=True, to='shop.Order'),
        ),
    ]
