# Generated by Django 2.2.28 on 2025-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20250319_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_to_deliver',
            field=models.DateTimeField(),
        ),
    ]
