# Generated by Django 2.2.28 on 2025-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20250319_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='products_to_deliver',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
