# Generated by Django 2.2.28 on 2025-03-19 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20250319_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_reference',
            field=models.ImageField(upload_to='product_img/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
