# Generated by Django 2.2.28 on 2025-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20250322_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_img',
            field=models.ImageField(default='profile_img/default.svg', upload_to='profile_img/'),
        ),
    ]
