# Generated by Django 2.2.28 on 2025-03-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20250324_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_img',
            field=models.ImageField(default='profile_img/default.jpg', upload_to='profile_img/'),
        ),
    ]
