# Generated by Django 2.2.28 on 2025-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20250327_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='seller_account',
            field=models.BooleanField(default=False),
        ),
    ]
